"""Shared fixtures/helpers for the STORY-001 automated test suite.

Signal-construction helpers implement the exact formulas specified in
test-cases.md so fixtures are deterministic and traceable back to a TC.
"""
from __future__ import annotations

import math
from pathlib import Path

import numpy as np
import pytest
import soundfile as sf

from suno_mastering.config import MasteringConfig

# Repo-root targets.json (regenerated by DEF-604 fix; required by DEF-606 fix).
# All pipeline tests that call master() must use a config with targets_json_path set.
_REPO_ROOT = Path(__file__).resolve().parents[4]
_TARGETS_JSON = str(_REPO_ROOT / "targets.json")


# ---------------------------------------------------------------------------
# Basic signal builders
# ---------------------------------------------------------------------------

def sine(freq: float, sr: int, duration_s: float, amplitude: float = 1.0, phase: float = 0.0) -> np.ndarray:
    n = int(round(duration_s * sr))
    t = np.arange(n) / sr
    return amplitude * np.sin(2 * np.pi * freq * t + phase)


def cosine(freq: float, sr: int, duration_s: float, amplitude: float = 1.0, phase: float = 0.0) -> np.ndarray:
    n = int(round(duration_s * sr))
    t = np.arange(n) / sr
    return amplitude * np.cos(2 * np.pi * freq * t + phase)


def to_stereo(mono: np.ndarray) -> np.ndarray:
    return np.stack([mono, mono], axis=1)


def nyquist_adjacent_sine(sr: int, duration_s: float, amplitude: float = 1.0) -> np.ndarray:
    """x[n] = amplitude * sin(pi*n/2 + pi/4), i.e. exactly sr/4 Hz with a
    45-degree phase offset (STORY-003 architecture.md Section 1.2/7.2).
    Every discrete sample lands at exactly +/- amplitude/sqrt(2) (sample
    peak exactly -3.0103 dBFS at amplitude=1.0), while the continuous-time
    signal's true peak of `amplitude` occurs at instants that fall exactly
    halfway between consecutive samples -- the classic, EXACT (not
    approximate) inter-sample-overshoot construction, giving an analytically
    known 3.0103 dB margin. Deliberately not a near-Nyquist frequency:
    true_peak.py's own documented FIR droop (~1.5 dB at 94% Nyquist) would
    corrupt the expected value there; sr/4 sits well inside the FIR's flat
    passband regardless of oversample factor."""
    n = int(round(duration_s * sr))
    return amplitude * np.sin(np.pi * np.arange(n) / 2.0 + np.pi / 4.0)


def dbfs_to_amplitude(dbfs: float) -> float:
    return 10 ** (dbfs / 20.0)


def rms_amplitude_for_dbfs_sine(dbfs: float) -> float:
    """Peak amplitude of a sine wave whose RMS equals `dbfs` dBFS."""
    rms = dbfs_to_amplitude(dbfs)
    return rms * math.sqrt(2)


def make_dynamic_track(
    sr: int,
    duration_s: float,
    body_amplitude: float = 0.1,
    transient_amplitude: float = 0.5,
    transient_period_s: float = 1.0,
    transient_len_ms: float = 5.0,
    freq: float = 220.0,
    stereo: bool = True,
) -> np.ndarray:
    """A body tone plus frequent, brief louder transients -- gives the
    fixture genuine, *robustly measurable* crest factor / DR (a pure
    constant-amplitude tone has ~DR0 and is an unresolvable-constraint
    fixture, not a representative-track fixture; a handful of very sparse
    single-sample spikes makes the DR-meter's "2nd highest peak" statistic
    fixture-length-sensitive). Many transients per 3s DR-meter block keeps
    the measurement stable regardless of exactly which block(s) the limiter
    touches most. Mirrors the TC-030 "two-level synthetic signal"
    construction note, tuned for robustness across short test fixtures.
    """
    body = sine(freq, sr, duration_s, amplitude=body_amplitude)
    n = len(body)
    period = max(1, int(round(transient_period_s * sr)))
    transient_len = max(1, int(round(transient_len_ms / 1000.0 * sr)))
    for start in range(period, n - transient_len, period):
        body[start:start + transient_len] = transient_amplitude
    if stereo:
        return to_stereo(body)
    return body


def write_wav(path, audio: np.ndarray, sr: int, subtype: str = "PCM_24"):
    sf.write(str(path), audio, sr, subtype=subtype)
    return str(path)


@pytest.fixture
def tmp_wav_dir(tmp_path):
    d = tmp_path / "wavs"
    d.mkdir()
    return d


@pytest.fixture
def default_config() -> MasteringConfig:
    """Default mastering config with targets_json_path set to repo-root targets.json.

    DEF-610 fix: targets_json_path is now required by the pipeline (DEF-606 fix),
    so default_config must include a valid path.  The repo-root targets.json is
    the regenerated file produced by the DEF-604 fix; it is valid for all story tests.
    """
    return MasteringConfig(targets_json_path=_TARGETS_JSON)


@pytest.fixture
def out_dir(tmp_path):
    d = tmp_path / "out"
    d.mkdir()
    return str(d)
