"""Offline calibration utility -- NOT part of the runtime pipeline
(architecture.md Section 8, item 1).

Given 3-5 producer-nominated reference WAVs the producer considers
well-mastered in the melodic progressive house/techno genre, computes each
track's Welch PSD in the three defined bands, normalizes each to its own
500Hz-2kHz average, averages across tracks, and writes a replacement
`progressive_house_124bpm.json` in the same schema as the shipped default.

Usage:
    python scripts/build_reference_curve.py track1.wav track2.wav ... \
        --output ../suno_mastering/reference/progressive_house_124bpm.json
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np
import soundfile as sf
from scipy.signal import welch

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from suno_mastering.config import MasteringConfig  # noqa: E402


def _band_power(freqs, psd, band_hz):
    lo, hi = band_hz
    mask = (freqs >= lo) & (freqs <= hi)
    if not mask.any():
        return 1e-20
    return max(float(np.trapezoid(psd[mask], freqs[mask])), 1e-20)


def _track_relative_bands(path: str, config: MasteringConfig) -> dict:
    audio, sr = sf.read(path, dtype="float64", always_2d=True)
    mono = audio.mean(axis=1)
    nperseg = int(min(65536, max(1024, 2 ** int(np.floor(np.log2(max(mono.size, 1024)))))))
    freqs, psd = welch(mono, fs=sr, nperseg=nperseg, noverlap=nperseg // 2, average="mean")

    ref_power = _band_power(freqs, psd, config.freq_reference_band_hz)
    return {
        "low_end": 10.0 * np.log10(_band_power(freqs, psd, config.freq_low_band_hz) / ref_power),
        "low_mid_mud": 10.0 * np.log10(_band_power(freqs, psd, config.freq_mud_band_hz) / ref_power),
        "presence_harsh": 10.0 * np.log10(_band_power(freqs, psd, config.freq_presence_band_hz) / ref_power),
    }


def build_reference_curve(track_paths: list, config: MasteringConfig = None) -> dict:
    config = config or MasteringConfig()
    per_track = [_track_relative_bands(p, config) for p in track_paths]

    averaged = {
        band: float(np.mean([t[band] for t in per_track]))
        for band in ("low_end", "low_mid_mud", "presence_harsh")
    }

    return {
        "genre": "melodic progressive house / melodic techno, 124 BPM",
        "description": (
            "Reference curve generated by scripts/build_reference_curve.py from "
            "producer-nominated reference tracks (see source_tracks)."
        ),
        "reference_band_hz": list(config.freq_reference_band_hz),
        "bands": {
            "low_end": {"range_hz": list(config.freq_low_band_hz), "relative_db": averaged["low_end"]},
            "low_mid_mud": {"range_hz": list(config.freq_mud_band_hz), "relative_db": averaged["low_mid_mud"]},
            "presence_harsh": {"range_hz": list(config.freq_presence_band_hz), "relative_db": averaged["presence_harsh"]},
        },
        "source_tracks": [str(Path(p).name) for p in track_paths],
        "generated_by": "scripts/build_reference_curve.py",
    }


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("tracks", nargs="+", help="3-5 producer-nominated reference WAV files.")
    parser.add_argument(
        "--output",
        default=str(Path(__file__).resolve().parent.parent / "suno_mastering" / "reference" / "progressive_house_124bpm.json"),
        help="Output path for the generated reference curve JSON.",
    )
    args = parser.parse_args(argv)

    if not (3 <= len(args.tracks) <= 5):
        print("Warning: spec recommends 3-5 reference tracks; proceeding anyway.", file=sys.stderr)

    curve = build_reference_curve(args.tracks)
    with open(args.output, "w", encoding="utf-8") as fh:
        json.dump(curve, fh, indent=2)
    print(f"Wrote reference curve to {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
